# TCL File Generated by Component Editor 17.1
# Tue Aug 14 19:08:09 CEST 2018
# DO NOT MODIFY


#
# mems_that_shit "mems_that_shit" v1.0
#  2018.08.14.19:08:09
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module mems_that_shit
#
set_module_property DESCRIPTION ""
set_module_property NAME mems_that_shit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mems_that_shit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MEMS_THAT_SHIT
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MEMS_THAT_SHIT.v VERILOG PATH ip/roboy_fpga_code/mems/MEMS_THAT_SHIT.v TOP_LEVEL_FILE


#
# parameters
#
add_parameter IDLE STD_LOGIC_VECTOR 0
set_parameter_property IDLE DEFAULT_VALUE 0
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE WIDTH 4
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:15
set_parameter_property IDLE HDL_PARAMETER true
add_parameter WAIT_FOR_TRANSMIT STD_LOGIC_VECTOR 1
set_parameter_property WAIT_FOR_TRANSMIT DEFAULT_VALUE 1
set_parameter_property WAIT_FOR_TRANSMIT DISPLAY_NAME WAIT_FOR_TRANSMIT
set_parameter_property WAIT_FOR_TRANSMIT WIDTH 4
set_parameter_property WAIT_FOR_TRANSMIT TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_FOR_TRANSMIT UNITS None
set_parameter_property WAIT_FOR_TRANSMIT ALLOWED_RANGES 0:15
set_parameter_property WAIT_FOR_TRANSMIT HDL_PARAMETER true
add_parameter MEM_SIZE STD_LOGIC_VECTOR 4096
set_parameter_property MEM_SIZE DEFAULT_VALUE 4096
set_parameter_property MEM_SIZE DISPLAY_NAME MEM_SIZE
set_parameter_property MEM_SIZE WIDTH 25
set_parameter_property MEM_SIZE TYPE STD_LOGIC_VECTOR
set_parameter_property MEM_SIZE UNITS None
set_parameter_property MEM_SIZE ALLOWED_RANGES 0:33554431
set_parameter_property MEM_SIZE HDL_PARAMETER true


#
# display items
#


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point avalon_master
#
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address address Output 32
add_interface_port avalon_master write_data writedata Output 256
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master write write Output 1


#
# connection point clock_sink
#
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


#
# connection point conduit_end
#
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end pdm pdm Input 1
add_interface_port conduit_end pdm_clk_out pdm_clk_out Output 1
add_interface_port conduit_end dec_clk_out dec_clk_out Output 1


#
# connection point pdm_clk
#
add_interface pdm_clk clock end
set_interface_property pdm_clk clockRate 0
set_interface_property pdm_clk ENABLED true
set_interface_property pdm_clk EXPORT_OF ""
set_interface_property pdm_clk PORT_NAME_MAP ""
set_interface_property pdm_clk CMSIS_SVD_VARIABLES ""
set_interface_property pdm_clk SVD_ADDRESS_GROUP ""

add_interface_port pdm_clk pdm_clk clk Input 1


#
# connection point dec_clk
#
add_interface dec_clk clock end
set_interface_property dec_clk clockRate 0
set_interface_property dec_clk ENABLED true
set_interface_property dec_clk EXPORT_OF ""
set_interface_property dec_clk PORT_NAME_MAP ""
set_interface_property dec_clk CMSIS_SVD_VARIABLES ""
set_interface_property dec_clk SVD_ADDRESS_GROUP ""

add_interface_port dec_clk dec_clk clk Input 1
